# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.srcs/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/lab7_1_block_hdmi_text_controller_0_11.xci
# IP: The module: 'lab7_1_block_hdmi_text_controller_0_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/hdmi_tx_0_2/hdmi_tx_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0_ooc.xdc

# IP: C:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.srcs/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/lab7_1_block_hdmi_text_controller_0_11.xci
# IP: The module: 'lab7_1_block_hdmi_text_controller_0_11' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/hdmi_tx_0_2/hdmi_tx_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==hdmi_tx_0 || ORIG_REF_NAME==hdmi_tx_0} -quiet] -quiet

# IP: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/src/clk_wiz_0_2/clk_wiz_0_ooc.xdc
