# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Lab7/mb_usb_hdmi_top.xdc

# Block Designs: bd/lab7_1_block/lab7_1_block.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block || ORIG_REF_NAME==lab7_1_block} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_microblaze_0_2/lab7_1_block_microblaze_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_microblaze_0_2 || ORIG_REF_NAME==lab7_1_block_microblaze_0_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_dlmb_v10_2/lab7_1_block_dlmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_dlmb_v10_2 || ORIG_REF_NAME==lab7_1_block_dlmb_v10_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_ilmb_v10_2/lab7_1_block_ilmb_v10_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_ilmb_v10_2 || ORIG_REF_NAME==lab7_1_block_ilmb_v10_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_dlmb_bram_if_cntlr_2/lab7_1_block_dlmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_dlmb_bram_if_cntlr_2 || ORIG_REF_NAME==lab7_1_block_dlmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_ilmb_bram_if_cntlr_2/lab7_1_block_ilmb_bram_if_cntlr_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_ilmb_bram_if_cntlr_2 || ORIG_REF_NAME==lab7_1_block_ilmb_bram_if_cntlr_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_lmb_bram_2/lab7_1_block_lmb_bram_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_lmb_bram_2 || ORIG_REF_NAME==lab7_1_block_lmb_bram_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_xbar_3/lab7_1_block_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_xbar_3 || ORIG_REF_NAME==lab7_1_block_xbar_3} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_microblaze_0_axi_periph_2/lab7_1_block_microblaze_0_axi_periph_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_microblaze_0_axi_periph_2 || ORIG_REF_NAME==lab7_1_block_microblaze_0_axi_periph_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_microblaze_0_axi_intc_2/lab7_1_block_microblaze_0_axi_intc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_microblaze_0_axi_intc_2 || ORIG_REF_NAME==lab7_1_block_microblaze_0_axi_intc_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_mdm_1_1/lab7_1_block_mdm_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_mdm_1_1 || ORIG_REF_NAME==lab7_1_block_mdm_1_1} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_clk_wiz_1_0 || ORIG_REF_NAME==lab7_1_block_clk_wiz_1_0} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_rst_clk_wiz_1_100M_1/lab7_1_block_rst_clk_wiz_1_100M_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==lab7_1_block_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_axi_uartlite_0_2/lab7_1_block_axi_uartlite_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_axi_uartlite_0_2 || ORIG_REF_NAME==lab7_1_block_axi_uartlite_0_2} -quiet] -quiet

# IP: bd/lab7_1_block/ip/lab7_1_block_hdmi_text_controller_0_11/lab7_1_block_hdmi_text_controller_0_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab7_1_block_hdmi_text_controller_0_11 || ORIG_REF_NAME==lab7_1_block_hdmi_text_controller_0_11} -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/lab7_1_block_ooc.xdc
