# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.srcs/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0.xci
# IP: The module: 'lab7_1_block_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_block_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_block_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_block_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.srcs/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0.xci
# IP: The module: 'lab7_1_block_clk_wiz_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_block_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_block_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/corey/UIUC/ECE/ECE385/Lab7/lab7/lab7.gen/sources_1/bd/lab7_1_block/ip/lab7_1_block_clk_wiz_1_0/lab7_1_block_clk_wiz_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab7_1_block_clk_wiz_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
